### ISSUE TITLE
Cache control : no cache

### ISSUE THREAD

**Issue by anujchourange** [1itromio/cowin-vaccine-booking#4]
Hey Mate I appreciate what you did. it is highi useful but in my district i am not able to find a slot and book it using such applications..
I think the reason for that is that cowin api developers have enabled cache response of 30 minutes... So it is not working in busy places...

I request you to set cache control to no if possible 
Thanks

**Comment by 1itromio** [comment]
Hey Anuj the app is meant to be used for such busy places and give a chance to normal people to get vaccine slots easily. About the cache it is only there for public APIs. As you use the app you must have seen the OTP automatically fetched and the session in renewed, we are using the bearer token to get the latest response, hence i believe the working principles are similar to the cowin website and 30 minutes cache rule theoretically should not apply. Only states and district fetching apis are cached for 24 hours else other APIs are not cached. There was one bug though which was not allowing the app to poll very frequently due to doze mode. However it is fixed in v1.0.1. Try it and let's hope it works.

**Comment by anujchourange** [comment]
Thanks mate
